[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = '0.8.20'
evm_version = 'paris'
optimizer = true
optimizer_runs = 4294967295
bytecode_hash = 'none'

[fmt]
line_length = 120
multiline_func_header = 'params_first'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
